# Generated by Django 4.1.7 on 2023-02-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('launch_date', models.DateTimeField(verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.TextField(blank=True, default=None, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
                ('supplier', models.PositiveSmallIntegerField(choices=[(0, 'Начальный'), (1, '1 уровень'), (2, '2 уровень'), (3, '3 уровень'), (4, '4 уровень')], verbose_name='Поставщик')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexus.productinfo', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
